language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-dev python-pip libxslt1-dev libxml2-dev
  - sudo pip install pygments
install:
  - git clone --depth=1 --branch=master https://github.com/tabatkins/bikeshed.git ./bikeshed
  - sudo pip install --editable ./bikeshed
  - bikeshed update
script:
  bikesped spec ./index.src.html
